### ISSUE TITLE
Ensure that the implementation of controllers supports control plane migration

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-vsphere#102]
**How to categorize this issue?**

/area control-plane-migration
/kind task
/kind test
/priority normal
/platform vsphere

**What would you like to be added**:
* Ensure that the implementation of this provider extension's controllers supports control plane migration properly, see https://github.com/gardener/gardener/blob/master/docs/extensions/migration.md.
* Test control plane migration manually with this provider extension as described in https://github.com/gardener/gardener/blob/master/docs/usage/control_plane_migration.md. You can also use the code of the existing integration test to trigger and test the migration in a more automated way, see https://github.com/gardener/gardener/blob/master/.test-defs/MigrateShoot.yaml.
* To enable the control plane migration, the `SeedChange` feature gate in Gardener API server should be switched on. Currently this is the case in a locally running `gardener-apiserver`, see https://github.com/gardener/gardener/blob/master/hack/local-development/start-apiserver

**Why is this needed**:

**Comment by MartinWeindel** [comment]
Nothing to do. Several vSphere clusters have been migrated successfully.
